---
- name: Configuración del servidor web
  hosts: all
  become: yes

  tasks:
    - name: Actualizar la caché de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started

    - name: Copiar archivos HTML al directorio por defecto de Apache
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
